#!/bin/bash

TESTS="./tests/*.grp"
GRAPE="./src/grape.native"

for TEST in $TESTS 
do

    RESULT=$(eval "$GRAPE $TEST | lli" 2>&1)
    OUT="${TEST%.*}.out"

    if [ ! -f $OUT ]; then
        echo "NO OUTFILE" && echo "$RESULT" > $OUT
    elif [ "$RESULT" == "$(cat $OUT)" ]; then
        echo "PASS $TEST"
    else
        echo "FAIL $TEST differs from $OUT"
    fi
done
exit
