#!/bin/bash

HOME="$1"
TESTS="./tests/*.grp"
GRAPE="./dist/grape"
GRAPENATIVE="./dist/grape.native"

for TEST in $TESTS 
do

    RESULT=$(eval "$GRAPE $TEST && ./out.g" 2>&1) 
    AST_RESULT=$(eval "$GRAPENATIVE -a $TEST" 2>&1)
    SAST_RESULT=$(eval "$GRAPENATIVE -s $TEST" 2>&1)

    rm $FAILFILE;
    OUTFILE="${TEST%.*}.out"
    FAILFILE="${TEST%.*}.fail"
    AST_OUTFILE="${TEST%.*}.ast.out"
    SAST_OUTFILE="${TEST%.*}.sast.out"

    if [ ! -f $OUTFILE ]; then
        echo "NO OUT" && echo "$RESULT" > $OUTFILE;
    else
        if [ "$RESULT" == "$(cat $OUTFILE)" ]; then
            echo "PASS $OUTFILE";
        else
            echo "FAIL $TEST differs from $OUTFILE";
            echo "OUT: " >> $FAILFILE
            echo $RESULT >> $FAILFILE; fi
    fi

    if [ ! -f $AST_OUTFILE ]; then
        echo "NO AST" && echo "$AST_RESULT" > $AST_OUTFILE
    else
        if [ "$AST_RESULT" == "$(cat $AST_OUTFILE)" ]; then
            echo "PASS $AST_OUTFILE";
        else
            echo "FAIL $TEST differs from $AST_OUTFILE";
            echo "AST: " >> $FAILFILE
            echo $AST_RESULT >> $FAILFILE; fi
    fi

    if [ ! -f $SAST_OUTFILE ]; then
        echo "NO SAST" && echo "$SAST_RESULT" > $SAST_OUTFILE
    else
        if [ "$SAST_RESULT" == "$(cat $SAST_OUTFILE)" ]; then
            echo "PASS $SAST_OUTFILE";
        else
            echo "FAIL $TEST differs from $SAST_OUTFILE";
            echo "SAST: " >> $FAILFILE
            echo $SAST_RESULT >> $FAILFILE; fi
    fi
done
exit
