#!/bin/bash

HOME=$(dirname "$0")
PROGRAM="$1"
OBJECT="${1%.*}.s"
OUTFILE=${2:-"./out.g"}

cat $HOME/grplib.grp "$1" | $HOME/grape.native | llc -relocation-model=pic > $OBJECT
cc -g -O -o $OUTFILE $OBJECT $HOME/stdlib.o

rm $OBJECT
chmod 750 $OUTFILE
